<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d3a763bc-a63a-4b2e-9cf5-7d9d533107f4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NearbyEats.Application\NearbyEats.Application.csproj" />
    <ProjectReference Include="..\NearbyEats.Infrastructure\NearbyEats.Infrastructure.csproj" />
  </ItemGroup>

</Project>
